### PR TITLE
Add option to auto-enable 'private' in Incognito Mode.

### PR DESCRIPTION
**Pull request by the-kenny**
Adds a feature to auto-check the 'private' checkbox when PinboardPlus is used in Incognito Mode.

### CODE REVIEW

**Comment by the-kenny** [comment]
If you're interested in it I want to extend this PR with another new setting that disables pinging the Pinboard API when running in Incognito Mode.

**Comment by clvrobj** [comment]
Thanks for the idea of auto-check the 'private' checkbox.
For disabling pinging the Pinboard API when running in Incognito Mode, I am worried about user might no aware that the extension are stop pinging the API in the mode and might think it is bug.
Let me merge this first.

**Comment by the-kenny** [comment]
Good thinking, it could really confuse users. Maybe we can show a small
icon + tooltip if it's disabled in incognito mode?

Am 04.12.2016 07:35 schrieb "Chi Zhang" <notifications@github.com>:

**Comment by clvrobj** [comment]
Yeah, I think badge + tooltip might be a solution.

**Pull request merged**
